
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Tangerine } from "next/font/google";
import { Montserrat } from "next/font/google";

export const tangerine = Tangerine({
  weight: ["400", "700"], 
  subsets: ["latin"], 
  display: "swap",
});

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat", // Add this
});


export const metadata = {
  title: "SangeeTru",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Header />
        <div className="min-h-[100vh] bg-white mx-w-[1200px] mx-auto">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
